// Add steps as necessary for accessing the software, post-configuration, and testing. Don’t include full usage instructions for your software, but add links to your product documentation for that information.
//Should any sections not be applicable, remove them

== Test the deployment
// If steps are required to test the deployment, add them here. If not, remove the heading
* Monitor the link:https://console.aws.amazon.com/cloudformation/home?region=us-east-1[AWS CloudFormation], link:https://console.aws.amazon.com/codesuite/codebuild/projects?region=us-east-1[AWS CodeBuild] and link:https://console.aws.amazon.com/codesuite/codepipeline/pipelines?region=us-east-1[AWS CodePipeline] in us-east-1 region and should not have any errors or failures. It will take approximate 90 minutes.


* Once finished go to link:https://console.aws.amazon.com/athena/home?region=us-east-1[Amazon Athena] link:https://docs.aws.amazon.com/IAM/latest/UserGuide/id_roles_use_switch-role-console.html[switch the role] on the top right to @-saw-datalake-users-, Ex. - @demoteam-saw-datalake-users-us-east-1. If using the default settings of the module, put the Account Id the same as the AWS Account Id being used. The Role name should be @demoteam-saw-datalake-users-us-east-1. Switch Amazon Athena workgroup to ---workgroup, EX - demoteam-demodl-dev-workgroup.


* Run the below queries to explore the sample AMC datasets

[,sql]
----
SELECT * FROM "demoteam_amcdataset_dev_stage"."testdemocustomer_time_to_conversion_adhoc" limit 10;
----

////
** SELECT * FROM "demoteam_amcdataset_dev_stage"."testdemocustomer_audience_analysis_adhoc" limit 10;
** SELECT * FROM "demoteam_amcdataset_dev_stage"."testdemocustomer_device_exposure_adhoc" limit 10;
** SELECT * FROM "demoteam_amcdataset_dev_stage"."testdemocustomer_frequency_distribution_adhoc" limit 10;
** SELECT * FROM "demoteam_amcdataset_dev_stage"."testdemocustomer_geo_analysis_adhoc" limit 10;
** SELECT * FROM "demoteam_amcdataset_dev_stage"."testdemocustomer_product_mix_adhoc" limit 10;
////

// == Post-deployment steps
// If post-deployment steps are required, add them here. If not, remove the heading
////
.Below are some sample QuickSight Dashboards built using the sample AMC datasets:
For more detailed configuration steps of the QuickSight dashboards, review the document located link:../docs/AMC_Analytics_Delivery_Kit-Quicksight_Instructions.pdf[QuickStart Dashboard Setup Guide]

* Audience Analysis
** This dashboard provides analysis on audience segments targeted by the customer and also details of audience segments that user was a part of but not targeted for purchases of customer products on Amazon.
* Frequency Distribution
** This dashboard provides analysis on performance and delivery by different frequencies/impression exposures to help optimize campaign frequency caps to maximize conversion likelihood for purchases of assigned customer products on Amazon.
* Device Exposure
** This dashboard helps to determine performance metrics (i.e., ROAS, Impressions, Conversions, Clicks) across device types (e.g., TV, Mobile, PC, Tablet) for purchases of assigned customer products on Amazon.
* Geo Analysis
** This dashboard provides analysis on performance data by geographic location (e.g.DMA) for purchases of assigned customer products on Amazon.
* Product Mix Analysis
** This dashboard provides performance data of users exposed to both sponsored products (SP) and display campaigns (DSP) and KPIs surrounding them.
////

== Building Your First QuickSight Dashboard with Reports from AMC
The AMC Dashboard provides an interactive visualization of marketing performance insights with the ability to slice the data by campaign, device type, DMA, frequency, audience segments, and time periods.
The dashboard’s goal is to provide a plethora of event level marketing insights in one visualized central location. The dashboard draws from a series of custom workflows built upon Demo Customer data available in AMC that are run on a daily basis. It has a text visual that describes how to read and understand the dashboard
The users can get read only permissions to this dashboard and can view relevant data visuals.
The dashboard shows metrics both numerically (in tabular form) and graphically (bar charts, stacked bar combo charts, maps, etc.) to enable quick insight discovery. This data can be exported into csv files for further analysis.

=== Initial QuickSight Setup
You will need author access to a QuickSight Account to get started with building your first dashboard. If you don't have a QuickSight account already, below are the steps to create one.

1. Launch the **AWS Console** (https://console.aws.amazon.com) in a new browser tab, search for **QuickSight** and launch it.
2. On the **QuickSight** page, click **Sign up for QuickSight** button.
3. Keep the default **Enterprise** edition, scroll down and click the **Continue** button.
4. Enter a **QuickSight account name** & **Notification email address**. Enter your official email as the notification email.
5. Scroll down and click the **Finish** button. (It can take 15-30 Secs to set up the account)
6. Click the **Go to Amazon QuickSight** button. You will now be taken to QuickSight console.

=== Authorize Your QuickSight Connection through AWS Lake Formation
Insert Steps to Get Signed up for QuickSight
https://docs.aws.amazon.com/quicksight/latest/user/lake-formation.html#lake-formation-lf-steps

=== Query & Visualize Your First AMC Use Case 
Amazon Marketing Cloud (AMC) enables advertisers to query event level data within a privacy friendly environment. Amazon QuickSight offers users a cloud-powered business analytics service to build visualizations, perform ad-hoc analysis, and quickly get business insights from their data.

#### Time to Conversion

Find out how long it takes for your customers to convert after last seeing your ad. It is important to understand how long it takes customers who see your ad to complete the conversion, and how that impacts the data you see in your conversion report. Sometimes the conversions happens rapidly, within a few minutes. Other times it might take days for your customers to complete the purchase. You can use this information to adjust the duration of campaign and promotion to maximize sales. In our amazon_attributed_events_by_conversion_time and amazon_attributed_events_by_traffic_time tables, we report up to 14 days after the customers’ last exposure to your ad.

#### Key Performance Indicators (KPIs):

|===
| KPI | Definition 

| Time to Conversion
| The amount of time customers take from last seeing your ad to purchase. The time has been converted to minutes, hours and days from seconds in the query template. You may adjust it based on your use case.

| Purchases
| The number of times any amount of a promoted product or products are included in a purchase event. Purchase events include video rentals and new Subscribe & Save subscriptions. Sum of purchases from users_that_purchased.

| Total Brand Purchases
| The number of times any number of products are included in a single purchase event. Purchase events include Subscribe & Save subscriptions and video rentals. This counts purchases for promoted products as well as products from the same brands as the products tracked in the order. (Total purchases = Purchases + Purchases Brand Halo)
|===


#### Creating the Visualization:
This section provides details on how to create a visualization for the Time to Conversion use case in Amazon QuickSight.

1. Begin by creating a new dataset. Choose **Datasets** from the navigation pane at left, then choose **New dataset**.
2. Next, connect to an Athena Data Source with either a using an existing connection profile (more common) or by creating a new one.
  A. To use an existing Athena connection profile, scroll down to the **FROM EXISTING DATA SOURCES** section, and choose the card for the existing data source that you want to use. Choose **Create dataset**. Cards are labeled with the Athena data source icon and the name provided by the person who created the connection.
  B. Next, create a new Athena connection profile, use the following steps:
    a. In the **FROM NEW DATA SOURCES** section, choose the **Athena** data source card.
    b. For **Data source name**, enter a descriptive name
    c. For **Athena workgroup**, choose your workgroup
    d. Choose **Validate connection** to test the connection
    e. Choose **Create data source**.
3. On the **Choose your table screen**, do the following:
  A. For **Catalog**, choose **AwsDataCatalog**.
  B. Choose one of the following:
    a. To write a SQL query, choose **Use custom SQL**
    b. To choose a database and table, choose your catalog that contains your databases from the dropdown under **Catalog**. Then, choose a database from the dropdown under **Database** and choose a table from the **Tables** list that appears for your database. Note: If you don't have the right permissions, you receive the following error message: "You don't have sufficient permissions to connect to this dataset or run this query." Contact your QuickSight administrator for assistance. For more information, see Authorizing connections to Amazon Athena: https://docs.aws.amazon.com/quicksight/latest/user/athena.html
4. Choose **Edit/preview data**.
5. Create a dataset and analyze the data using the table by choosing **Visualize**. 
6. In the **Fields list** pane, choose **purchases**, **time_to_conversion**, and **total_brand_purchases**.
7. Amazon QuickSight uses AutoGraph to create the visual, selecting the visual type that it determines is most compatible with those fields. In this case, it selects a horizontal bar chart that shows the purchases and total_brand_purchases by time_to_conversion.
8. In the **Visual types** pane, select **Vertical bar chart** to rotate the chart.
9. Expand the **Field wells** pane by choosing the expand icon.
10. Choose the **X axis** field well, choose **Sort by**, and then choose **time_to_conversion**. 
11. Again from the **X axis** field well, select **ascending** icon.




//== Best practices for using {partner-product-short-name} on AWS
// Provide post-deployment best practices for using the technology on AWS, including considerations such as migrating data, backups, ensuring high performance, high availability, etc. Link to software documentation for detailed information.

//_Add any best practices for using the software._

//== Security
// Provide post-deployment best practices for using the technology on AWS, including considerations such as migrating data, backups, ensuring high performance, high availability, etc. Link to software documentation for detailed information.

//_Add any security-related information._

//== Other useful information
//Provide any other information of interest to users, especially focusing on areas where AWS or cloud usage differs from on-premises usage.

//_Add any other details that will help the customer use the software on AWS._
